unit ExtUxData;

// Generated by ExtToPascal v.0.9.8, at 6/1/2010 11:41:27
// from "C:\Trabalho\ext-3.0.0\docs\output" detected as ExtJS v.3

interface

uses
  StrUtils, ExtPascal, ExtPascalUtils, ExtData;

type
  TExtUxDataPagingMemoryProxy = class;

  TExtUxDataPagingMemoryProxy = class(TExtDataMemoryProxy)
  public
    function JSClassName : string; override;
    {$IFDEF FPC}constructor AddTo(List : TExtObjectList);{$ENDIF}
  end;

implementation

function TExtUxDataPagingMemoryProxy.JSClassName : string; begin
  Result := 'Ext.ux.data.PagingMemoryProxy';
end;

{$IFDEF FPC}constructor TExtUxDataPagingMemoryProxy.AddTo(List : TExtObjectList);begin inherited end;{$ENDIF}

end.